Revert "CHROMIUM: Merge remote-tracking branch 'upstream/main' into HEAD"
This reverts commit 758715ce4c448f6824160a0e904aa966c9b951d8, reversing
changes made to 11b785b2a56f17300cdfefee626110019d688dcd.

BUG=b:284952721
TEST=https://spellingclassroom.com/SpellingMission_demo/index.html

Change-Id: Ie48e7e0e2dd1a64445de1c9ea27baac4168af7a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/4588602
Reviewed-by: Chia-I Wu <olv@google.com>
Tested-by: Rob Clark <robdclark@chromium.org>
Commit-Queue: Chia-I Wu <olv@google.com>
Auto-Submit: Rob Clark <robdclark@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/mesa/+/4598278
Reviewed-by: Ilja Friedel <ihf@chromium.org>
Commit-Queue: Ilja Friedel <ihf@chromium.org>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,16 +1,3 @@
-workflow:
-  rules:
-    - if: $GITLAB_USER_LOGIN == "marge-bot" && $CI_COMMIT_BRANCH == null
-      variables:
-        MESA_CI_PERFORMANCE_ENABLED: 1
-    - if: $GITLAB_USER_LOGIN == "marge-bot" && $CI_COMMIT_BRANCH
-      variables:
-        LAVA_JOB_PRIORITY: 40
-    - if: $GITLAB_USER_LOGIN != "marge-bot"
-      variables:
-        LAVA_JOB_PRIORITY: 50
-    - when: always
-
 variables:
   FDO_UPSTREAM_REPO: mesa/mesa
   MESA_TEMPLATES_COMMIT: &ci-templates-commit d5aa3941aa03c2f716595116354fb81eb8012acb
@@ -33,7 +20,7 @@ variables:
   FD_FARM: "online"
   COLLABORA_FARM: "online"
   MICROSOFT_FARM: "online"
-  LIMA_FARM: "offline"
+  LIMA_FARM: "online"
   IGALIA_FARM: "online"
   ANHOLT_FARM: "online"
   VALVE_FARM: "online"
@@ -41,13 +28,10 @@ variables:
 
 default:
   before_script:
-    - >
-      export SCRIPTS_DIR=$(mktemp -d) &&
-      curl -L -s --retry 4 -f --retry-all-errors --retry-delay 60 -O --output-dir "${SCRIPTS_DIR}" "${CI_PROJECT_URL}/-/raw/${CI_COMMIT_SHA}/.gitlab-ci/setup-test-env.sh" &&
-      chmod +x ${SCRIPTS_DIR}/setup-test-env.sh &&
-      . ${SCRIPTS_DIR}/setup-test-env.sh &&
-      echo -n "${CI_JOB_JWT}" > "${CI_JOB_JWT_FILE}" &&
-      unset CI_JOB_JWT  # Unsetting vulnerable env variables
+    - echo -e "\e[0Ksection_start:$(date +%s):unset_env_vars_section[collapsed=true]\r\e[0KUnsetting vulnerable environment variables"
+    - echo -n "${CI_JOB_JWT}" > "${CI_JOB_JWT_FILE}"
+    - unset CI_JOB_JWT
+    - echo -e "\e[0Ksection_end:$(date +%s):unset_env_vars_section\r\e[0K"
 
   after_script:
     - >
@@ -57,10 +41,11 @@ default:
       export CI_JOB_JWT="$(<${CI_JOB_JWT_FILE})" &&
       rm "${CI_JOB_JWT_FILE}"
 
-  # Retry when job fails. Failed jobs can be found in the Mesa CI Daily Reports:
-  # https://gitlab.freedesktop.org/mesa/mesa/-/issues/?sort=created_date&state=opened&label_name%5B%5D=CI%20daily
+  # Retry build or test jobs up to twice when the gitlab-runner itself fails somehow.
   retry:
-    max: 1
+    max: 2
+    when:
+      - runner_system_failure
 
 include:
   - project: 'freedesktop/ci-templates'
@@ -79,7 +64,6 @@ include:
   - local: '.gitlab-ci/build/gitlab-ci.yml'
   - local: '.gitlab-ci/test/gitlab-ci.yml'
   - local: '.gitlab-ci/test-source-dep.yml'
-  - local: 'docs/gitlab-ci.yml'
   - local: 'src/amd/ci/gitlab-ci.yml'
   - local: 'src/broadcom/ci/gitlab-ci.yml'
   - local: 'src/etnaviv/ci/gitlab-ci.yml'
@@ -122,6 +106,15 @@ stages:
 # --------------------------------
 .rules-anchors:
   rules:
+    # Pipeline for forked project branch
+    - if: &is-forked-branch '$CI_COMMIT_BRANCH && $CI_PROJECT_NAMESPACE != "mesa"'
+      when: manual
+    # Forked project branch / pre-merge pipeline not for Marge bot
+    - if: &is-forked-branch-or-pre-merge-not-for-marge '$CI_PROJECT_NAMESPACE != "mesa" || ($GITLAB_USER_LOGIN != "marge-bot" && $CI_PIPELINE_SOURCE == "merge_request_event")'
+      when: manual
+    # Pipeline runs for the main branch of the upstream Mesa project
+    - if: &is-mesa-main '$CI_PROJECT_NAMESPACE == "mesa" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH'
+      when: always
     # Post-merge pipeline
     - if: &is-post-merge '$CI_PROJECT_NAMESPACE == "mesa" && $CI_COMMIT_BRANCH'
       when: on_success
@@ -136,6 +129,71 @@ stages:
       when: on_success
 
 
+.docs-base:
+  variables:
+    BUILDER: html
+  extends:
+    - .fdo.ci-fairy
+    - .build-rules
+  artifacts:
+    expose_as: 'Documentation preview'
+    paths:
+    - public/
+  script:
+  - apk --no-cache add graphviz doxygen
+  - pip3 install sphinx===5.1.1 breathe===4.34.0 mako===1.2.3 sphinx_rtd_theme===1.0.0
+  - docs/doxygen-wrapper.py --out-dir=docs/doxygen_xml
+  - sphinx-build -W -b $BUILDER docs public
+
+pages:
+  extends: .docs-base
+  stage: deploy
+  needs: []
+  rules:
+    - !reference [.no_scheduled_pipelines-rules, rules]
+    - if: *is-mesa-main
+      changes: &docs-or-ci
+      - docs/**/*
+      - .gitlab-ci.yml
+      when: always
+    # Other cases default to never
+
+test-docs:
+  extends: .docs-base
+  # Cancel job if a newer commit is pushed to the same branch
+  interruptible: true
+  stage: deploy
+  needs: []
+  rules:
+    - !reference [.no_scheduled_pipelines-rules, rules]
+    - if: *is-forked-branch
+      changes: *docs-or-ci
+      when: manual
+    # Other cases default to never
+
+test-docs-mr:
+  extends:
+    - test-docs
+  needs:
+    - sanity
+  rules:
+    - if: *is-pre-merge
+      changes: *docs-or-ci
+      when: on_success
+    # Other cases default to never
+
+lincheck-docs:
+  extends: .docs-base
+  # Cancel job if a newer commit is pushed to the same branch
+  interruptible: true
+  stage: deploy
+  needs: []
+  rules:
+    - !reference [.scheduled_pipeline-rules, rules]
+  allow_failure: true
+  variables:
+    BUILDER: linkcheck
+
 # When to automatically run the CI for build jobs
 .build-rules:
   rules:
@@ -145,6 +203,7 @@ stages:
       - VERSION
       - bin/git_sha1_gen.py
       - bin/install_megadrivers.py
+      - bin/meson_get_version.py
       - bin/symbols-check.py
       # GitLab CI
       - .gitlab-ci.yml
@@ -238,3 +297,22 @@ sanity:
     when: on_failure
     reports:
       junit: check-*.xml
+
+# Temporary rules for tests that should not block merging, but should be
+# available to optionally run with the "play" button in the UI in pre-merge
+# non-marge pipelines.  This should appear in "extends:" after any includes of
+# test-source-dep.yml rules, so that these rules replace those.
+#
+# If a job is going to be manual for a long period of time, then please use a
+# driver-specific manual rules set from test-source-dep (see
+# freedreno-manual-rules, for example)
+.test-manual-mr:
+  rules:
+    - !reference [.no_scheduled_pipelines-rules, rules]
+    - if: *is-forked-branch-or-pre-merge-not-for-marge
+      changes:
+        *all_paths
+      when: manual
+  variables:
+    JOB_TIMEOUT: 80
+
